# Generated by Django 5.2.4 on 2025-07-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_admin_notes_complaint_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='complaint_attachments/'),
        ),
    ]
